import { createBrowserRouter, Link, useNavigate } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Bot, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, Flame, GraduationCap, LayoutDashboard, LogOut, Megaphone, MessageSquare, Plus, Search, Settings, ShieldCheck, Sparkles, Target, Trophy, UserPlus, Users, Share2 } from "lucide-react";

const SUPABASE_URL="https://knzuhcccujtwzlhbsbss.supabase.co";
const SUPABASE_KEY="sb_publishable_zXs9CoVPbqA_DbrEsHKMvg_RwHUByQC";
const STAGES=["Descoberto","Qualificado","Contatado","Respondeu","Interessado","Candidatura","Entrevista","Family","Desafio Fênix","Agency","Ativação","Performance"];
const stageKey=s=>({"Desafio Fênix":"desafio","Ativação":"ativacao"}[s]||s.toLowerCase());
const stageLabel=s=>({descoberto:"Descoberto",qualificado:"Qualificado",contatado:"Contatado",respondeu:"Respondeu",interessado:"Interessado",candidatura:"Candidatura",entrevista:"Entrevista",family:"Family",familia:"Family",desafio:"Desafio Fênix",challenge:"Desafio Fênix",agency:"Agency",agencia:"Agency",ativacao:"Ativação",performance:"Performance"}[(s||"").toLowerCase()]||s||"Descoberto");

async function sb(path,{method="GET",body,token,prefer}={}){
  const r=await fetch(`${SUPABASE_URL}${path}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token||SUPABASE_KEY}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})},body:body?JSON.stringify(body):undefined});
  if(!r.ok){let msg=`Erro ${r.status}`;try{const e=await r.json();msg=e.message||e.error_description||e.details||msg}catch{}throw new Error(msg)}
  if(r.status===204)return null; const t=await r.text(); return t?JSON.parse(t):null;
}
const token=()=>sessionStorage.getItem("fenix_token")||"";
const user=()=>{try{return JSON.parse(sessionStorage.getItem("fenix_user")||"{}")}catch{return {}}};

function Login(){
  const nav=useNavigate(); const[email,setEmail]=useState(""); const[password,setPassword]=useState(""); const[err,setErr]=useState(""); const[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setErr("");try{const d=await sb("/auth/v1/token?grant_type=password",{method:"POST",body:{email,password}});sessionStorage.setItem("fenix_token",d.access_token);sessionStorage.setItem("fenix_user",JSON.stringify(d.user||{}));nav("/")}catch{setErr("Não foi possível entrar. Verifique e-mail e senha.")}finally{setBusy(false)}}
  return <div className="auth-page"><form className="auth-card" onSubmit={submit}><div className="crest big">🔥</div><p>NOVA ERA</p><h1>FÊNIX OS 2.0</h1><span>Central operacional de recrutamento, desenvolvimento e performance.</span><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?"Entrando...":"Entrar no ecossistema"}</button><Link to="/candidatura">Quero ser Streamer Fênix</Link></form></div>
}

function Candidatura(){
  const[done,setDone]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");
  const[f,setF]=useState({nome:"",contato:"",cidade:"",estado:"",objetivo:"",nichos:"",origem:"Landing Page"});
  async function submit(e){e.preventDefault();setBusy(true);setErr("");try{await sb("/rest/v1/leads",{method:"POST",prefer:"return=minimal",body:{nome:f.nome,contato:f.contato,cidade:f.cidade,estado:f.estado,objetivo:f.objetivo,origem:f.origem,nichos:f.nichos.split(",").map(x=>x.trim()).filter(Boolean),adulto_confirmado:true,consentiu_contato:true,estagio:"candidatura"}});setDone(true)}catch{setErr("Não foi possível enviar agora. Tente novamente.")}finally{setBusy(false)}}
  if(done)return <div className="public-page"><div className="public-card success"><CheckCircle2 size={56}/><p>CANDIDATURA RECEBIDA</p><h1>Sua jornada Fênix começou.</h1><span>Nossa equipe analisará seu perfil. A inscrição não garante contratação. Buscamos pessoas 18+ comprometidas com lives, eventos e evolução.</span><Link className="primary" to="/login">Área da equipe</Link></div></div>;
  return <div className="public-page"><form className="public-card" onSubmit={submit}><span className="eyebrow"><Flame size={14}/> QUERO SER FÊNIX</span><h1>Transforme lives em projeto.</h1><p>Seleção para pessoas 18+ que desejam aprender, participar de eventos e construir performance no universo das lives.</p><div className="grid2"><label>Nome completo<input required value={f.nome} onChange={e=>setF({...f,nome:e.target.value})}/></label><label>WhatsApp ou e-mail<input required value={f.contato} onChange={e=>setF({...f,contato:e.target.value})}/></label><label>Cidade<input value={f.cidade} onChange={e=>setF({...f,cidade:e.target.value})}/></label><label>Estado<input value={f.estado} onChange={e=>setF({...f,estado:e.target.value})}/></label></div><label>Nichos / interesses<input placeholder="Música, entretenimento, lifestyle..." value={f.nichos} onChange={e=>setF({...f,nichos:e.target.value})}/></label><label>Por que você quer trabalhar com lives?<textarea required value={f.objetivo} onChange={e=>setF({...f,objetivo:e.target.value})}/></label><label className="check"><input type="checkbox" required/> Confirmo que tenho 18 anos ou mais e autorizo contato da Fênix Warriors sobre esta candidatura.</label>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?"Enviando...":"Enviar candidatura"}</button><small>Sem promessa de ganhos. Resultados dependem de atividade, audiência, regras da plataforma e desempenho individual.</small></form></div>
}

const NAV=[["Central",LayoutDashboard],["Talent Hunter",Search],["CRM",Users],["Entrevistas",ClipboardCheck],["Campanhas",Megaphone],["Mensagens",MessageSquare],["Social Hub",Share2],["Academy",GraduationCap],["Eventos",CalendarDays],["Performance",BarChart3],["Configurações",Settings]];
const MODULES=[["FÊNIX TALENT","Descoberta, seleção e contratação",UserPlus,"Talent Hunter"],["FÊNIX FAMILY","Comunidade, integração e cultura",Users,"CRM"],["FÊNIX ACADEMY","Formação e Desafio Fênix",GraduationCap,"Academy"],["FÊNIX AGENCY","Gestão profissional e metas",ShieldCheck,"Performance"],["FÊNIX LIVE","Eventos e ativações",CalendarDays,"Eventos"],["FÊNIX AI","Priorização e decisões",Bot,"Central"]];

function Dashboard(){
  const nav=useNavigate(); const t=token();
  const[tab,setTab]=useState("Central"); const[q,setQ]=useState(""); const[loading,setLoading]=useState(true); const[error,setError]=useState("");
  const[leads,setLeads]=useState([]); const[campaigns,setCampaigns]=useState([]); const[templates,setTemplates]=useState([]); const[social,setSocial]=useState([]); const[interviews,setInterviews]=useState([]); const[challenges,setChallenges]=useState([]); const[events,setEvents]=useState([]); const[metrics,setMetrics]=useState([]); const[scoreRules,setScoreRules]=useState([]); const[profile,setProfile]=useState(null);
  const[modal,setModal]=useState(null); const[selected,setSelected]=useState(null);

  async function load(){if(!t){nav("/login");return}setLoading(true);setError("");const u=user();const calls=[
    sb("/rest/v1/leads?select=*&order=created_at.desc&limit=250",{token:t}),
    sb("/rest/v1/fw_talent_campaigns?select=*&order=created_at.desc",{token:t}),
    sb("/rest/v1/fw_message_templates?select=*&order=created_at.desc",{token:t}),
    sb("/rest/v1/fw_social_accounts_safe?select=*&order=updated_at.desc",{token:t}),
    sb("/rest/v1/fw_interviews?select=*&order=scheduled_at.desc&limit=100",{token:t}),
    sb("/rest/v1/fw_challenges?select=*&order=created_at.desc",{token:t}),
    sb("/rest/v1/fw_events?select=*&order=starts_at.desc&limit=100",{token:t}),
    sb("/rest/v1/fw_streamer_metrics?select=*&order=metric_date.desc&limit=200",{token:t}),
    sb("/rest/v1/fw_score_rules?select=*&order=weight.desc",{token:t}),
    u.id?sb(`/rest/v1/admin_profiles?user_id=eq.${u.id}&select=*`,{token:t}):Promise.resolve([])
  ]; const r=await Promise.allSettled(calls); const sets=[setLeads,setCampaigns,setTemplates,setSocial,setInterviews,setChallenges,setEvents,setMetrics,setScoreRules]; sets.forEach((fn,i)=>{if(r[i].status==="fulfilled")fn(r[i].value||[])}); if(r[9]?.status==="fulfilled")setProfile(r[9].value?.[0]||null);setLoading(false)}
  useEffect(()=>{load()},[]);

  const filtered=useMemo(()=>leads.filter(x=>`${x.nome} ${x.origem||""} ${x.cidade||""} ${x.estado||""} ${(x.nichos||[]).join(" ")}`.toLowerCase().includes(q.toLowerCase())),[leads,q]);
  const priority=leads.filter(x=>(x.fenix_score||0)>=75).length; const avg=priority?Math.round(leads.filter(x=>(x.fenix_score||0)>=75).reduce((a,b)=>a+(b.fenix_score||0),0)/priority):0;
  const byStage=s=>leads.filter(l=>stageLabel(l.estagio)===s).length;
  async function saveLead(form,id){try{if(id){const rows=await sb(`/rest/v1/leads?id=eq.${id}`,{method:"PATCH",token:t,prefer:"return=representation",body:form});setLeads(leads.map(x=>x.id===id?rows[0]:x))}else{const rows=await sb("/rest/v1/leads",{method:"POST",token:t,prefer:"return=representation",body:{...form,adulto_confirmado:true,consentiu_contato:true}});setLeads([rows[0],...leads])}setModal(null)}catch(e){alert(e.message)}}
  async function moveStage(lead,stage){try{const rows=await sb(`/rest/v1/leads?id=eq.${lead.id}`,{method:"PATCH",token:t,prefer:"return=representation",body:{estagio:stageKey(stage)}});setLeads(leads.map(x=>x.id===lead.id?rows[0]:x));setSelected(rows[0])}catch(e){alert(e.message)}}
  async function saveCampaign(form){try{const rows=await sb("/rest/v1/fw_talent_campaigns",{method:"POST",token:t,prefer:"return=representation",body:form});setCampaigns([rows[0],...campaigns]);setModal(null)}catch(e){alert(e.message)}}
  async function saveInterview(form){try{const rows=await sb("/rest/v1/fw_interviews",{method:"POST",token:t,prefer:"return=representation",body:form});setInterviews([rows[0],...interviews]);await moveStage(leads.find(l=>l.id===Number(form.lead_id)),"Entrevista");setModal(null)}catch(e){alert(e.message)}}
  async function saveEvent(form){try{const rows=await sb("/rest/v1/fw_events",{method:"POST",token:t,prefer:"return=representation",body:form});setEvents([rows[0],...events]);setModal(null)}catch(e){alert(e.message)}}
  async function enrollChallenge(lead){if(!challenges[0])return alert("Nenhum desafio ativo.");try{await sb("/rest/v1/fw_challenge_enrollments",{method:"POST",token:t,prefer:"return=representation",body:{challenge_id:challenges[0].id,lead_id:lead.id,status:"active"}});await moveStage(lead,"Desafio Fênix");alert("Candidato inscrito no Desafio Fênix.")}catch(e){alert(e.message)}}
  function logout(){sessionStorage.clear();nav("/login")}

  return <div className="shell"><aside><div className="brand"><div className="crest">🔥</div><div><b>FÊNIX WARRIORS</b><span>NOVA ERA • OS 2.0</span></div></div><nav>{NAV.map(([n,I])=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}><I size={18}/>{n}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={16}/> Sair</button><div className="aside-foot"><Sparkles size={17}/><div><b>{profile?.display_name||"Fênix AI"}</b><small>{profile?.role?`Acesso ${profile.role}`:"Decisão orientada por dados"}</small></div></div></aside>
  <main><header><div><p>ECOSSISTEMA DE DESENVOLVIMENTO DE STREAMERS</p><h1>{tab}</h1></div><div className="header-actions"><Link className="ghost link" to="/candidatura">Candidatura</Link><button className="primary" onClick={()=>setModal(tab==="Eventos"?"event":"lead")}><Plus size={18}/> Novo</button></div></header>{error&&<div className="error">{error}</div>}

  {tab==="Central"&&<><section className="hero"><div><span className="eyebrow"><Flame size={14}/> OPERAÇÃO ATIVA</span><h2>Do primeiro contato à<br/><em>performance.</em></h2><p>O FÊNIX OS centraliza descoberta, seleção, entrevistas, desenvolvimento, eventos e métricas em uma única jornada.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab("Talent Hunter")}>Buscar talentos <ChevronRight size={17}/></button><button className="ghost" onClick={()=>setTab("CRM")}>Abrir funil</button></div></div><div className="score"><span>FÊNIX SCORE</span><strong>{avg||"--"}</strong><small>Média dos talentos 75+</small></div></section>
  <section className="kpis">{[["Talentos",leads.length,loading?"carregando":"base real"],["Prioridade 75+",priority,"Fênix Score"],["Entrevistas",interviews.length,"registradas"],["Eventos",events.length,"agenda"],["Métricas",metrics.length,"registros"]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</section><div className="section-title"><div><p>UMA JORNADA</p><h3>Estrutura Fênix Warriors</h3></div></div><section className="modules">{MODULES.map(([n,d,I,dest])=><article key={n}><div className="module-icon"><I/></div><h4>{n}</h4><p>{d}</p><button onClick={()=>setTab(dest)}>Acessar <ChevronRight size={15}/></button></article>)}</section></>}

  {tab==="Talent Hunter"&&<><section className="page-intro"><div><p>PROSPECÇÃO INTELIGENTE</p><h2>Talent Hunter</h2><span>Talentos 18+ avaliados por aderência profissional.</span></div><button className="primary" onClick={()=>setModal("lead")}><UserPlus size={18}/> Adicionar talento</button></section><section className="filters"><input placeholder="Buscar nome, rede, cidade ou nicho..." value={q} onChange={e=>setQ(e.target.value)}/><select onChange={e=>setQ(e.target.value)}><option value="">Todas origens</option><option>TikTok</option><option>Instagram</option><option>Facebook</option><option>Indicação</option></select><select onChange={e=>setQ(e.target.value)}><option value="">Todos locais</option><option>SP</option><option>RJ</option><option>MG</option><option>ES</option></select><select onChange={e=>setQ(e.target.value)}><option value="">Todos nichos</option><option>Entretenimento</option><option>Música</option><option>Lifestyle</option></select></section><LeadTable data={filtered} onOpen={setSelected}/></>}

  {tab==="CRM"&&<><section className="page-intro"><div><p>PIPELINE COMPLETO</p><h2>Funil de talentos</h2><span>Da descoberta à performance, sem planilhas paralelas.</span></div></section><section className="pipeline">{STAGES.map((s,i)=><article key={s}><small>{String(i+1).padStart(2,"0")}</small><b>{s}</b><strong>{byStage(s)}</strong></article>)}</section><LeadTable data={leads} onOpen={setSelected}/></>}

  {tab==="Entrevistas"&&<><section className="page-intro"><div><p>SELEÇÃO HUMANA</p><h2>Entrevistas</h2><span>Registre agenda, avaliação e recomendação.</span></div><button className="primary" onClick={()=>setModal("interview")}><Plus size={18}/> Agendar</button></section><DataTable headers={["Data","Candidato","Status","Score","Recomendação"]} rows={interviews.map(i=>[new Date(i.scheduled_at).toLocaleString("pt-BR"),leads.find(l=>l.id===i.lead_id)?.nome||`Lead ${i.lead_id}`,i.status,i.score??"—",i.recommendation||"—"])} /></>}

  {tab==="Campanhas"&&<><section className="page-intro"><div><p>AQUISIÇÃO</p><h2>Campanhas de Talentos</h2><span>Metas, canais e regiões em um único lugar.</span></div><button className="primary" onClick={()=>setModal("campaign")}><Plus size={18}/> Nova campanha</button></section><Cards items={campaigns.map(c=>({title:c.name,badge:c.status,body:`Meta: ${c.goal_qualified||0} qualificados\nRegiões: ${(c.target_regions||[]).join(", ")||"Brasil"}\nCanais: ${(c.channels||[]).join(", ")||"—"}`}))} empty="Crie a primeira campanha."/></>}

  {tab==="Mensagens"&&<><section className="page-intro"><div><p>COMUNICAÇÃO</p><h2>Biblioteca de Mensagens</h2><span>Templates para abordagem e follow-up com aprovação humana.</span></div></section><Cards items={templates.map(x=>({title:x.name,badge:x.channel,body:x.body}))} empty="Nenhum template."/></>}

  {tab==="Social Hub"&&<><section className="page-intro"><div><p>INTEGRAÇÕES OFICIAIS</p><h2>Social Hub</h2><span>Conecte somente por OAuth e APIs autorizadas. Tokens nunca aparecem no painel.</span></div></section><Cards items={social.map(x=>({title:x.account_name||x.platform,badge:x.connected?"Conectado":"Pendente",body:`${x.platform}\n${x.connection_status||"not_connected"}`}))} empty="Nenhuma conta conectada. Autorize Instagram/Facebook/TikTok pelas credenciais oficiais da Fênix para ativar publicação ou mensageria permitida."/><div className="notice">A busca e a comunicação não utilizam scraping invasivo nem automação que contorne limites das plataformas. Quando a API não permite DM automática, o sistema gera tarefa para execução humana.</div></>}

  {tab==="Academy"&&<><section className="page-intro"><div><p>FORMAÇÃO</p><h2>Fênix Academy</h2><span>Desafio Fênix e desenvolvimento do candidato.</span></div></section><Cards items={challenges.map(x=>({title:x.name,badge:x.active?"Ativo":"Inativo",body:`Duração: ${x.duration_days} dias\nUse a ficha do candidato para inscrevê-lo.`}))} empty="Nenhum desafio cadastrado."/></>}

  {tab==="Eventos"&&<><section className="page-intro"><div><p>FÊNIX LIVE</p><h2>Eventos</h2><span>Agenda oficial e interna.</span></div><button className="primary" onClick={()=>setModal("event")}><Plus size={18}/> Novo evento</button></section><DataTable headers={["Evento","Tipo","Data","Plataforma","Oficial"]} rows={events.map(e=>[e.name,e.event_type,new Date(e.starts_at).toLocaleString("pt-BR"),e.platform||"—",e.official?"Sim":"Não"])} /></>}

  {tab==="Performance"&&<><section className="page-intro"><div><p>RESULTADO</p><h2>Performance</h2><span>Atividade, metas e evolução dos streamers.</span></div></section><section className="kpis compact">{[["Registros",metrics.length],["Minutos de live",metrics.reduce((a,b)=>a+(b.live_minutes||0),0)],["Beans",Math.round(metrics.reduce((a,b)=>a+Number(b.beans||0),0))],["Eventos",metrics.reduce((a,b)=>a+(b.events_count||0),0)]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></article>)}</section><DataTable headers={["Data","Streamer","Minutos","Beans","Seguidores","Eventos"]} rows={metrics.slice(0,100).map(m=>[m.metric_date,m.user_id?.slice(0,8)||"—",m.live_minutes||0,m.beans||0,m.followers_gain||0,m.events_count||0])}/></>}

  {tab==="Configurações"&&<><section className="page-intro"><div><p>ADMINISTRAÇÃO</p><h2>Configurações</h2><span>Fênix Score, acesso e governança.</span></div></section><div className="settings-grid"><section className="settings-card"><h3>Perfil de acesso</h3><p>{profile?.display_name||user().email||"Usuário"}</p><span>{profile?.role||"authenticated"}</span></section><section className="settings-card"><h3>Regras do Fênix Score</h3>{scoreRules.map(r=><div className="rule" key={r.key}><span>{r.label}</span><b>{r.weight}</b></div>)}</section><section className="settings-card"><h3>Segurança</h3><p>RLS ativo nas estruturas Nova Era. Integrações sociais permanecem bloqueadas até OAuth oficial.</p></section></div></>}
  </main>

  {selected&&<LeadDrawer lead={selected} onClose={()=>setSelected(null)} onMove={s=>moveStage(selected,s)} onEdit={()=>setModal("editLead")} onChallenge={()=>enrollChallenge(selected)}/>} 
  {modal==="lead"&&<LeadModal onClose={()=>setModal(null)} onSave={f=>saveLead(f)} />}
  {modal==="editLead"&&selected&&<LeadModal lead={selected} onClose={()=>setModal(null)} onSave={f=>saveLead(f,selected.id)} />}
  {modal==="campaign"&&<CampaignModal onClose={()=>setModal(null)} onSave={saveCampaign}/>} 
  {modal==="interview"&&<InterviewModal leads={leads} onClose={()=>setModal(null)} onSave={saveInterview}/>} 
  {modal==="event"&&<EventModal onClose={()=>setModal(null)} onSave={saveEvent}/>} 
  </div>
}

function LeadTable({data,onOpen}){return <section className="table"><div className="tr head"><span>Talento</span><span>Origem</span><span>Local</span><span>Nicho</span><span>Score</span><span>Etapa</span></div>{data.length?data.map(x=><button className="tr rowbtn" key={x.id} onClick={()=>onOpen(x)}><span><b>{x.nome}</b><small>{x.contato||"sem contato"}</small></span><span>{x.origem||"—"}</span><span>{[x.cidade,x.estado].filter(Boolean).join("/")||"—"}</span><span>{(x.nichos||[]).join(", ")||"—"}</span><span><i className={`score-pill ${(x.fenix_score||0)>=75?"hot":""}`}>{x.fenix_score||0}</i></span><span><i className="stage">{stageLabel(x.estagio)}</i></span></button>):<div className="empty">Nenhum talento encontrado.</div>}</section>}
function DataTable({headers,rows}){return <div className="simple-table"><div className="simple-row simple-head">{headers.map(h=><span key={h}>{h}</span>)}</div>{rows.length?rows.map((r,i)=><div className="simple-row" key={i}>{r.map((c,j)=><span key={j}>{String(c)}</span>)}</div>):<div className="empty">Nenhum registro.</div>}</div>}
function Cards({items,empty}){return <section className="data-cards">{items.length?items.map((x,i)=><article key={i}><span>{x.badge}</span><h3>{x.title}</h3><p>{x.body}</p></article>):<div className="empty-card">{empty}</div>}</section>}
function LeadDrawer({lead,onClose,onMove,onEdit,onChallenge}){return <div className="drawer-bg" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><p className="eyebrow">FICHA DO TALENTO</p><h2>{lead.nome}</h2><div className="lead-score"><strong>{lead.fenix_score||0}</strong><span>Fênix Score</span></div><dl><dt>Contato</dt><dd>{lead.contato||"—"}</dd><dt>Origem</dt><dd>{lead.origem||"—"}</dd><dt>Local</dt><dd>{[lead.cidade,lead.estado].filter(Boolean).join("/")||"—"}</dd><dt>Nichos</dt><dd>{(lead.nichos||[]).join(", ")||"—"}</dd><dt>Objetivo</dt><dd>{lead.objetivo||"—"}</dd></dl><label>Etapa<select value={stageLabel(lead.estagio)} onChange={e=>onMove(e.target.value)}>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><div className="drawer-actions"><button className="ghost" onClick={onEdit}>Editar</button><button className="primary" onClick={onChallenge}>Iniciar Desafio</button></div></aside></div>}

function LeadModal({lead,onClose,onSave}){const[f,setF]=useState({nome:lead?.nome||"",contato:lead?.contato||"",origem:lead?.origem||"Indicação",cidade:lead?.cidade||"",estado:lead?.estado||"",objetivo:lead?.objetivo||"",fenix_score:lead?.fenix_score||0,nichos:(lead?.nichos||[]).join(", "),estagio:lead?.estagio||"descoberto"});function submit(e){e.preventDefault();onSave({...f,fenix_score:Number(f.fenix_score),nichos:f.nichos.split(",").map(x=>x.trim()).filter(Boolean)})}return <Modal onClose={onClose}><form onSubmit={submit}><p className="eyebrow">{lead?"EDITAR TALENTO":"NOVO TALENTO"}</p><h2>{lead?lead.nome:"Adicionar ao Talent Hunter"}</h2><div className="grid2"><label>Nome<input required value={f.nome} onChange={e=>setF({...f,nome:e.target.value})}/></label><label>Contato<input value={f.contato} onChange={e=>setF({...f,contato:e.target.value})}/></label><label>Origem<select value={f.origem} onChange={e=>setF({...f,origem:e.target.value})}><option>Indicação</option><option>Instagram</option><option>TikTok</option><option>Facebook</option><option>YouTube</option><option>BIGO</option><option>Landing Page</option></select></label><label>Fênix Score<input type="number" min="0" max="100" value={f.fenix_score} onChange={e=>setF({...f,fenix_score:e.target.value})}/></label><label>Cidade<input value={f.cidade} onChange={e=>setF({...f,cidade:e.target.value})}/></label><label>Estado<input value={f.estado} onChange={e=>setF({...f,estado:e.target.value})}/></label></div><label>Nichos<input value={f.nichos} onChange={e=>setF({...f,nichos:e.target.value})}/></label><label>Objetivo<textarea value={f.objetivo} onChange={e=>setF({...f,objetivo:e.target.value})}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary">Salvar</button></div></form></Modal>}
function CampaignModal({onClose,onSave}){const[f,setF]=useState({name:"Expansão Fênix",status:"active",target_regions:["Brasil"],min_age:18,max_age:35,niches:["Entretenimento"],desired_traits:["Disponibilidade","Consistência","Interesse profissional"],goal_qualified:30,channels:["Instagram","TikTok"]});function submit(e){e.preventDefault();onSave(f)}return <Modal onClose={onClose}><form onSubmit={submit}><p className="eyebrow">NOVA CAMPANHA</p><h2>Campanha Talent Hunter</h2><label>Nome<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><div className="grid2"><label>Idade mínima<input type="number" min="18" value={f.min_age} onChange={e=>setF({...f,min_age:Number(e.target.value)})}/></label><label>Idade máxima<input type="number" min="18" value={f.max_age} onChange={e=>setF({...f,max_age:Number(e.target.value)})}/></label></div><label>Meta de qualificados<input type="number" value={f.goal_qualified} onChange={e=>setF({...f,goal_qualified:Number(e.target.value)})}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary">Criar campanha</button></div></form></Modal>}
function InterviewModal({leads,onClose,onSave}){const[f,setF]=useState({lead_id:leads[0]?.id||"",scheduled_at:"",status:"scheduled",score:0,recommendation:"",notes:""});function submit(e){e.preventDefault();onSave({...f,lead_id:Number(f.lead_id),score:Number(f.score),scheduled_at:new Date(f.scheduled_at).toISOString()})}return <Modal onClose={onClose}><form onSubmit={submit}><p className="eyebrow">ENTREVISTA</p><h2>Agendar entrevista</h2><label>Candidato<select value={f.lead_id} onChange={e=>setF({...f,lead_id:e.target.value})}>{leads.map(l=><option key={l.id} value={l.id}>{l.nome}</option>)}</select></label><label>Data e hora<input type="datetime-local" required value={f.scheduled_at} onChange={e=>setF({...f,scheduled_at:e.target.value})}/></label><div className="grid2"><label>Score<input type="number" min="0" max="100" value={f.score} onChange={e=>setF({...f,score:e.target.value})}/></label><label>Recomendação<select value={f.recommendation} onChange={e=>setF({...f,recommendation:e.target.value})}><option value="">A avaliar</option><option>Aprovar</option><option>Nutrir</option><option>Recusar</option></select></label></div><label>Notas<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary">Agendar</button></div></form></Modal>}
function EventModal({onClose,onSave}){const[f,setF]=useState({name:"",event_type:"internal",starts_at:"",platform:"BIGO LIVE",official:false});function submit(e){e.preventDefault();onSave({...f,starts_at:new Date(f.starts_at).toISOString()})}return <Modal onClose={onClose}><form onSubmit={submit}><p className="eyebrow">FÊNIX LIVE</p><h2>Novo evento</h2><label>Nome<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><div className="grid2"><label>Tipo<select value={f.event_type} onChange={e=>setF({...f,event_type:e.target.value})}><option value="internal">Interno</option><option value="platform">Plataforma</option></select></label><label>Data e hora<input type="datetime-local" required value={f.starts_at} onChange={e=>setF({...f,starts_at:e.target.value})}/></label></div><label>Plataforma<input value={f.platform} onChange={e=>setF({...f,platform:e.target.value})}/></label><label className="check"><input type="checkbox" checked={f.official} onChange={e=>setF({...f,official:e.target.checked})}/> Evento oficial da plataforma</label><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary">Criar evento</button></div></form></Modal>}
function Modal({children,onClose}){return <div className="modal-bg" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}>{children}</div></div>}

export default createBrowserRouter([{path:"/login",element:<Login/>},{path:"/candidatura",element:<Candidatura/>},{path:"*",element:<Dashboard/>}]);