import { createBrowserRouter, Link, useNavigate } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Bot, CalendarDays, CheckCircle2, ChevronRight, Flame, GraduationCap, LayoutDashboard, LogOut, Megaphone, MessageSquare, Search, Settings, ShieldCheck, Sparkles, Target, Trophy, UserPlus, Users, Share2 } from "lucide-react";

const SUPABASE_URL="https://knzuhcccujtwzlhbsbss.supabase.co";
const SUPABASE_KEY="sb_publishable_zXs9CoVPbqA_DbrEsHKMvg_RwHUByQC";
const stages=["Descoberto","Qualificado","Contatado","Respondeu","Interessado","Candidatura","Entrevista","Family","Desafio Fênix","Agency","Ativação","Performance"];
const stageMap={descoberto:"Descoberto",qualificado:"Qualificado",contatado:"Contatado",respondeu:"Respondeu",interessado:"Interessado",candidatura:"Candidatura",entrevista:"Entrevista",family:"Family",familia:"Family",challenge:"Desafio Fênix",desafio:"Desafio Fênix",agency:"Agency",agencia:"Agency",ativacao:"Ativação",performance:"Performance"};
const fallbackLeads=[{id:"d1",nome:"Talento demonstrativo",origem:"TikTok",cidade:"São Paulo",estado:"SP",fenix_score:88,estagio:"qualificado",nichos:["Lifestyle"],created_at:new Date().toISOString()}];

async function sb(path,{method="GET",body,token,prefer}={}){
 const r=await fetch(`${SUPABASE_URL}${path}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token||SUPABASE_KEY}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})},body:body?JSON.stringify(body):undefined});
 if(!r.ok){let msg=`Erro ${r.status}`;try{const e=await r.json();msg=e.message||e.msg||e.error_description||msg}catch{}throw new Error(msg)}
 if(r.status===204)return null;const txt=await r.text();return txt?JSON.parse(txt):null;
}
function getToken(){return sessionStorage.getItem("fenix_token")||""}

function Login(){const nav=useNavigate();const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[err,setErr]=useState("");const[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setErr("");try{const data=await sb("/auth/v1/token?grant_type=password",{method:"POST",body:{email,password}});sessionStorage.setItem("fenix_token",data.access_token);sessionStorage.setItem("fenix_user",JSON.stringify(data.user||{}));nav("/")}catch(e){setErr("Não foi possível entrar. Verifique e-mail e senha.")}finally{setBusy(false)}}return <div className="auth-page"><form className="auth-card" onSubmit={submit}><div className="crest big">🔥</div><p>NOVA ERA</p><h1>FÊNIX OS 2.0</h1><span>Central de crescimento e desenvolvimento de streamers.</span><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Senha<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} /></label>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?"Entrando...":"Entrar no ecossistema"}</button><Link to="/candidatura">Quero ser Streamer Fênix</Link></form></div>}

function Candidatura(){const[done,setDone]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");const[f,setF]=useState({nome:"",contato:"",cidade:"",estado:"",objetivo:"",origem:"Landing Page",nichos:""});async function submit(e){e.preventDefault();setBusy(true);setErr("");try{await sb("/rest/v1/leads",{method:"POST",prefer:"return=minimal",body:{nome:f.nome,contato:f.contato,cidade:f.cidade,estado:f.estado,objetivo:f.objetivo,origem:f.origem,nichos:f.nichos.split(",").map(x=>x.trim()).filter(Boolean),adulto_confirmado:true,consentiu_contato:true,estagio:"candidatura"}});setDone(true)}catch(e){setErr("Não foi possível enviar agora. Tente novamente em instantes.")}finally{setBusy(false)}}if(done)return <div className="public-page"><div className="public-card success"><CheckCircle2 size={56}/><p>CANDIDATURA RECEBIDA</p><h1>Sua jornada Fênix começou.</h1><span>Nossa equipe analisará seu perfil. A inscrição não garante contratação; buscamos pessoas 18+ comprometidas com lives, eventos, evolução e profissionalização.</span><Link className="primary" to="/login">Área da equipe</Link></div></div>;return <div className="public-page"><form className="public-card" onSubmit={submit}><span className="eyebrow"><Flame size={14}/> QUERO SER FÊNIX</span><h1>Transforme lives em projeto.</h1><p>Estamos selecionando pessoas 18+ que desejam aprender, participar de eventos e construir performance no universo das lives.</p><div className="grid2"><label>Nome completo<input required value={f.nome} onChange={e=>setF({...f,nome:e.target.value})}/></label><label>WhatsApp ou e-mail<input required value={f.contato} onChange={e=>setF({...f,contato:e.target.value})}/></label><label>Cidade<input value={f.cidade} onChange={e=>setF({...f,cidade:e.target.value})}/></label><label>Estado<input value={f.estado} onChange={e=>setF({...f,estado:e.target.value})}/></label></div><label>Nichos / interesses<input placeholder="Música, entretenimento, lifestyle..." value={f.nichos} onChange={e=>setF({...f,nichos:e.target.value})}/></label><label>Por que você quer trabalhar com lives?<textarea required value={f.objetivo} onChange={e=>setF({...f,objetivo:e.target.value})}/></label><label className="check"><input type="checkbox" required/> Confirmo que tenho 18 anos ou mais e autorizo contato da Fênix Warriors sobre esta candidatura.</label>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?"Enviando...":"Enviar candidatura"}</button><small>Sem promessa de ganhos. Resultados dependem de atividade, audiência, regras da plataforma e desempenho individual.</small></form></div>}

const modules=[["FÊNIX TALENT","Descoberta, seleção e contratação de novos talentos",UserPlus,"Talent Hunter"],["FÊNIX FAMILY","Comunidade, integração e descoberta de potencial",Users,"Family"],["FÊNIX ACADEMY","Formação, trilhas, cursos e certificações",GraduationCap,"Academy"],["FÊNIX AGENCY","Gestão profissional, metas e evolução",ShieldCheck,"Performance"],["FÊNIX LIVE","Eventos internos, oficiais, desafios e competições",CalendarDays,"Eventos"],["FÊNIX AI","Copiloto de recrutamento e estratégias",Bot,"Fênix AI"]];
const nav=[["Central",LayoutDashboard],["Talent Hunter",Search],["CRM",Users],["Campanhas",Megaphone],["Mensagens",MessageSquare],["Social Hub",Share2],["Academy",GraduationCap],["Eventos",CalendarDays],["Performance",BarChart3],["Configurações",Settings]];

function Dashboard(){const navTo=useNavigate();const[tab,setTab]=useState("Central");const[query,setQuery]=useState("");const[campaignModal,setCampaignModal]=useState(false);const[leads,setLeads]=useState([]);const[campaigns,setCampaigns]=useState([]);const[templates,setTemplates]=useState([]);const[social,setSocial]=useState([]);const[loading,setLoading]=useState(true);const token=getToken();
 useEffect(()=>{if(!token){navTo("/login");return}Promise.allSettled([sb("/rest/v1/leads?select=id,nome,origem,cidade,estado,fenix_score,estagio,nichos,created_at&order=created_at.desc&limit=100",{token}),sb("/rest/v1/fw_talent_campaigns?select=*&order=created_at.desc",{token}),sb("/rest/v1/fw_message_templates?select=id,name,channel,stage,body,active&order=created_at.desc",{token}),sb("/rest/v1/fw_social_accounts_safe?select=*&order=updated_at.desc",{token})]).then(r=>{if(r[0].status==="fulfilled")setLeads(r[0].value||[]);if(r[1].status==="fulfilled")setCampaigns(r[1].value||[]);if(r[2].status==="fulfilled")setTemplates(r[2].value||[]);if(r[3].status==="fulfilled")setSocial(r[3].value||[])}).finally(()=>setLoading(false))},[token,navTo]);
 const filtered=useMemo(()=>leads.filter(x=>`${x.nome} ${x.origem} ${x.cidade} ${(x.nichos||[]).join(" ")}`.toLowerCase().includes(query.toLowerCase())),[leads,query]);
 const priority=leads.filter(x=>x.fenix_score>=75).length;const avg=priority?Math.round(leads.filter(x=>x.fenix_score>=75).reduce((a,b)=>a+b.fenix_score,0)/priority):0;
 function logout(){sessionStorage.clear();navTo("/login")}
 async function createCampaign(data){const rows=await sb("/rest/v1/fw_talent_campaigns",{method:"POST",token,prefer:"return=representation",body:data});setCampaigns([...(rows||[]),...campaigns]);setCampaignModal(false);setTab("Campanhas")}
 return <div className="shell"><aside><div className="brand"><div className="crest">🔥</div><div><b>FÊNIX WARRIORS</b><span>NOVA ERA • OS 2.0</span></div></div><nav>{nav.map(([n,I])=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}><I size={18}/>{n}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={16}/> Sair</button><div className="aside-foot"><Sparkles size={17}/><div><b>Fênix AI</b><small>Decisão orientada por dados</small></div></div></aside><main><header><div><p>ECOSSISTEMA DE DESENVOLVIMENTO DE STREAMERS</p><h1>{tab}</h1></div><div className="header-actions"><Link className="ghost link" to="/candidatura">Candidatura</Link><button className="primary" onClick={()=>setCampaignModal(true)}><Target size={18}/> Nova campanha</button></div></header>
 {tab==="Central"&&<><section className="hero"><div><span className="eyebrow"><Flame size={14}/> A NOVA ERA COMEÇOU</span><h2>Não buscamos quantidade.<br/><em>Desenvolvemos performance.</em></h2><p>Descubra talentos, qualifique candidatos, forme streamers e acompanhe sua evolução em um único ecossistema.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab("Talent Hunter")}>Buscar talentos <ChevronRight size={17}/></button><button className="ghost" onClick={()=>setTab("CRM")}>Abrir funil</button></div></div><div className="score"><span>FÊNIX SCORE</span><strong>{avg||"--"}</strong><small>Média real dos talentos prioritários</small></div></section><section className="kpis">{[["Talentos",leads.length,loading?"carregando":"base real"],["Prioridade 75+",priority,"Fênix Score"],["Campanhas",campaigns.length,"registradas"],["Templates",templates.length,"comunicação"],["Redes",social.length,"configuradas"]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></article>)}</section><div className="section-title"><div><p>UM ECOSSISTEMA, UMA JORNADA</p><h3>Estrutura Fênix Warriors</h3></div></div><section className="modules">{modules.map(([n,d,I,dest])=><article key={n}><div className="module-icon"><I/></div><h4>{n}</h4><p>{d}</p><button onClick={()=>setTab(dest)}>Acessar <ChevronRight size={15}/></button></article>)}</section></>}
 {tab==="Talent Hunter"&&<><section className="page-intro"><div><p>PROSPECÇÃO INTELIGENTE</p><h2>Talent Hunter</h2><span>Organize talentos 18+ encontrados por canais autorizados e avalie critérios profissionais.</span></div><button className="primary" onClick={()=>setCampaignModal(true)}><UserPlus size={18}/> Criar busca</button></section><section className="filters"><input placeholder="Buscar nome, rede, cidade ou nicho..." value={query} onChange={e=>setQuery(e.target.value)}/><select><option>18+ • todas as faixas</option><option>18–24</option><option>25–34</option><option>35+</option></select><select><option>Brasil • todas regiões</option><option>Sudeste</option><option>Sul</option><option>Nordeste</option></select><select><option>Todos os nichos</option><option>Entretenimento</option><option>Música</option><option>Lifestyle</option></select></section><LeadTable data={filtered}/></>}
 {tab==="CRM"&&<><section className="page-intro"><div><p>PIPELINE COMPLETO</p><h2>Funil de talentos</h2><span>Da descoberta à performance, com candidatura, Family, desafio e Agency.</span></div></section><section className="pipeline">{stages.map((s,i)=><article key={s}><small>{String(i+1).padStart(2,"0")}</small><b>{s}</b><strong>{leads.filter(l=>(stageMap[(l.estagio||"").toLowerCase()]||l.estagio)===s).length}</strong></article>)}</section><LeadTable data={leads}/></>}
 {tab==="Campanhas"&&<DataCards title="Campanhas de Talentos" subtitle="Aquisição e seleção orientadas por perfil profissional." items={campaigns.map(c=>({title:c.name,badge:c.status||"draft",body:`Meta: ${c.goal_qualified||0} qualificados • ${(c.target_regions||[]).join(", ")||"Brasil"}` }))} empty="Crie a primeira campanha da Nova Era."/>}
 {tab==="Mensagens"&&<DataCards title="Biblioteca de Comunicação" subtitle="Templates com aprovação humana quando o canal exigir." items={templates.map(t=>({title:t.name,badge:t.channel,body:t.body}))} empty="Nenhum template disponível."/>}
 {tab==="Social Hub"&&<DataCards title="Social Hub" subtitle="Conexões oficiais. Tokens nunca são exibidos no painel." items={social.map(s=>({title:s.account_name||s.platform,badge:s.connected?"conectado":"não conectado",body:`${s.platform} • ${s.connection_status||"não configurado"}`}))} empty="Nenhuma conta conectada. Configure APIs oficiais antes de habilitar automações."/>}
 {!['Central','Talent Hunter','CRM','Campanhas','Mensagens','Social Hub'].includes(tab)&&<Generic tab={tab}/>} </main>{campaignModal&&<CampaignModal onClose={()=>setCampaignModal(false)} onSave={createCampaign}/>}</div>}

function LeadTable({data}){return <section className="table"><div className="tr head"><span>Talento</span><span>Origem</span><span>Local</span><span>Nicho</span><span>Score</span><span>Etapa</span></div>{data.length?data.map(x=><div className="tr" key={x.id}><span><b>{x.nome}</b><small>{new Date(x.created_at).toLocaleDateString("pt-BR")}</small></span><span>{x.origem||"—"}</span><span>{[x.cidade,x.estado].filter(Boolean).join("/")||"—"}</span><span>{(x.nichos||[])[0]||"—"}</span><span><i className={`score-pill ${x.fenix_score>=75?"hot":""}`}>{x.fenix_score||0}</i></span><span><i className="stage">{stageMap[(x.estagio||"").toLowerCase()]||x.estagio||"Descoberto"}</i></span></div>):<div className="empty">Nenhum talento encontrado.</div>}</section>}
function DataCards({title,subtitle,items,empty}){return <><section className="page-intro"><div><p>MÓDULO OPERACIONAL</p><h2>{title}</h2><span>{subtitle}</span></div></section><section className="data-cards">{items.length?items.map((x,i)=><article key={i}><span>{x.badge}</span><h3>{x.title}</h3><p>{x.body}</p></article>):<div className="empty-card">{empty}</div>}</section></>}
function CampaignModal({onClose,onSave}){const[f,setF]=useState({name:"Expansão Fênix",status:"active",target_regions:["Brasil"],min_age:18,max_age:35,niches:["Entretenimento","Música","Lifestyle"],desired_traits:["Frequência","Comunicação","Interesse em monetização"],goal_qualified:100,channels:["instagram","tiktok","facebook"]});return <div className="modal-bg" onClick={onClose}><form className="modal" onSubmit={e=>{e.preventDefault();onSave(f)}} onClick={e=>e.stopPropagation()}><span className="eyebrow">NOVA CAMPANHA</span><h2>Expansão Fênix</h2><p>Busca 18+ baseada em critérios profissionais, sem inferência de atributos sensíveis.</p><label>Nome<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><div className="grid2"><label>Idade mínima<input type="number" min="18" value={f.min_age} onChange={e=>setF({...f,min_age:Number(e.target.value)})}/></label><label>Idade máxima<input type="number" min="18" value={f.max_age} onChange={e=>setF({...f,max_age:Number(e.target.value)})}/></label></div><label>Nichos<input value={f.niches.join(", ")} onChange={e=>setF({...f,niches:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label>Meta de qualificados<input type="number" min="0" value={f.goal_qualified} onChange={e=>setF({...f,goal_qualified:Number(e.target.value)})}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Cancelar</button><button className="primary">Criar campanha</button></div></form></div>}
function Generic({tab}){const map={Academy:[GraduationCap,"Fênix Academy","Trilhas, Desafio Fênix de 7 dias, avaliações e certificações."],Eventos:[Trophy,"Fênix Live","Agenda de eventos oficiais e internos, presença, desafios e ranking."],Performance:[BarChart3,"Performance","Atividade, metas, retenção, evolução e indicadores dos streamers."],Configurações:[Settings,"Administração","Usuários, recrutadores, permissões, integrações e auditoria."],"Fênix AI":[Bot,"Fênix AI","Copiloto para priorização, follow-ups, insights e estratégia."]};const [I,title,desc]=map[tab]||map.Configurações;return <section className="generic"><I size={46}/><p>MÓDULO FÊNIX OS</p><h2>{title}</h2><span>{desc}</span><div className="feature-grid">{["Visão executiva","Fluxos e automações","Permissões por função","Histórico e auditoria","Indicadores","Exportação de dados"].map(x=><div key={x}><CheckCircle2 size={18}/>{x}</div>)}</div></section>}

export default createBrowserRouter([{path:"/login",element:<Login/>},{path:"/candidatura",element:<Candidatura/>},{path:"*",element:<Dashboard/>}]);