package br.com.agenciafenixwarriors.liveai;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.concurrent.Executors;

public class OverlayService extends Service {
    private WindowManager wm; private View bubble,teleprompterView; private TextView advice,metrics; private LinearLayout controls;
    private int viewers=0,comments=0,followers=0,gifts=0,stars=0,pk=0; private long beans=0,goalBeans=0,startMs;
    private String script="",token="",userId="",bigoId="",sessionId=null; private final java.util.concurrent.ExecutorService io=Executors.newSingleThreadExecutor(); private final SupabaseApi api=new SupabaseApi();
    private boolean compact=false,featureGoals=true,featureTeleprompter=true,featureStars=true,featurePk=true;
    private final Handler handler=new Handler(Looper.getMainLooper()); private int lastAutoCoachMinute=-1;
    private final Runnable ticker=new Runnable(){ public void run(){ refreshCoach(); int m=minutes(); if(m>0&&m%5==0&&m!=lastAutoCoachMinute){ lastAutoCoachMinute=m; advice.setText("AUTO COACH • "+m+" MIN\n"+CoachEngine.advise(m,viewers,beans,comments,followers,gifts,featureStars?stars:0,featurePk?pk:0,featureGoals?goalBeans:0)); saveSnapshot(); } handler.postDelayed(this,30000); }};

    @Override public void onCreate(){ super.onCreate(); createChannel(); startMs=SystemClock.elapsedRealtime(); startForeground(4242,new Notification.Builder(this,"fenix_live_ai").setContentTitle("FÊNIX LIVE AI ativo").setContentText("Coach e ferramentas disponíveis sobre a BIGO").setSmallIcon(android.R.drawable.star_big_on).build()); handler.post(ticker); }
    @Override public int onStartCommand(Intent i,int flags,int startId){ if(i!=null){ goalBeans=i.getLongExtra("goalBeans",0); script=nvl(i.getStringExtra("script")); token=nvl(i.getStringExtra("token")); userId=nvl(i.getStringExtra("userId")); bigoId=nvl(i.getStringExtra("bigoId")); api.setAccessToken(token); featureGoals=i.getBooleanExtra("feature_goals",true); featureTeleprompter=i.getBooleanExtra("feature_teleprompter",true); featureStars=i.getBooleanExtra("feature_stars",true); featurePk=i.getBooleanExtra("feature_pk",true); if(!featureGoals)goalBeans=0; if(!featureTeleprompter)script=""; } if(bubble==null)showBubble(); if(sessionId==null&&!token.isEmpty()&&!userId.isEmpty()&&!bigoId.isEmpty())io.execute(()->{try{sessionId=api.startSession(userId,bigoId,goalBeans);}catch(Exception ignored){}}); return START_NOT_STICKY; }
    private String nvl(String s){return s==null?"":s;} private int minutes(){return (int)Math.max(0,(SystemClock.elapsedRealtime()-startMs)/60000L);} private int overlayType(){return Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;}
    private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("fenix_live_ai","FÊNIX LIVE AI",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
    private TextView t(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sp);v.setPadding(16,10,16,10);return v;} private Button b(String s){Button v=new Button(this);v.setText(s);v.setAllCaps(false);return v;}

    private void showBubble(){
        wm=(WindowManager)getSystemService(WINDOW_SERVICE); LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(8,8,8,8); GradientDrawable bg=new GradientDrawable();bg.setColor(0xF0111114);bg.setCornerRadius(30);bg.setStroke(2,0xFFE24A2A);box.setBackground(bg);
        TextView head=t("🐦‍🔥 FÊNIX LIVE AI",18);box.addView(head); metrics=t("Sessão iniciada",13);box.addView(metrics); advice=t("Coach ativo. O sistema revisa sua live automaticamente a cada 5 minutos.",14);box.addView(advice); controls=new LinearLayout(this);controls.setOrientation(LinearLayout.VERTICAL);box.addView(controls);
        Button coach=b("🧠 COACH AGORA"),plan=b("🗺️ PLANO 10 MIN"),dynamic=b("🎯 DINÂMICA AGORA"),data=b("📊 ATUALIZAR DADOS"),gift=b("🎁 META / PRESENTES"),star=b("⭐ ESTRATÉGIA STARS"),pkb=b("⚔️ ESTRATÉGIA PK"),tele=b("📝 TELEPROMPTER"),mini=b("— MINIMIZAR"),close=b("ENCERRAR COACH");
        controls.addView(coach);controls.addView(plan);controls.addView(dynamic);controls.addView(data);controls.addView(gift);if(featureStars)controls.addView(star);if(featurePk)controls.addView(pkb);if(featureTeleprompter)controls.addView(tele);controls.addView(mini);controls.addView(close);
        coach.setOnClickListener(v->{refreshCoach();saveSnapshot();}); plan.setOnClickListener(v->advice.setText(CoachEngine.tenMinutePlan(minutes(),viewers,beans,comments,followers,gifts,goalBeans))); dynamic.setOnClickListener(v->advice.setText(CoachEngine.dynamicIdea(minutes()+comments+gifts)));
        data.setOnClickListener(v->showDataDialog()); gift.setOnClickListener(v->showGiftMenu()); if(featureStars)star.setOnClickListener(v->advice.setText(CoachEngine.starStrategy(stars,viewers,beans))); if(featurePk)pkb.setOnClickListener(v->advice.setText(CoachEngine.pkStrategy(viewers,pk))); if(featureTeleprompter)tele.setOnClickListener(v->toggleTeleprompter()); mini.setOnClickListener(v->toggleCompact(head)); close.setOnClickListener(v->stopSelf());
        WindowManager.LayoutParams lp=new WindowManager.LayoutParams(520,-2,overlayType(),WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP|Gravity.END;lp.x=12;lp.y=160;
        head.setOnTouchListener(new View.OnTouchListener(){float x,y;int ox,oy;public boolean onTouch(View v,MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){x=e.getRawX();y=e.getRawY();ox=lp.x;oy=lp.y;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){lp.x=ox-(int)(e.getRawX()-x);lp.y=oy+(int)(e.getRawY()-y);wm.updateViewLayout(box,lp);return true;}if(e.getAction()==MotionEvent.ACTION_UP){if(Math.abs(e.getRawX()-x)<12&&Math.abs(e.getRawY()-y)<12)toggleCompact(head);return true;}return false;}}); bubble=box;wm.addView(bubble,lp);refreshCoach();
    }
    private void toggleCompact(TextView head){compact=!compact;controls.setVisibility(compact?View.GONE:View.VISIBLE);advice.setVisibility(compact?View.GONE:View.VISIBLE);metrics.setVisibility(compact?View.GONE:View.VISIBLE);head.setText(compact?"🐦‍🔥 FÊNIX":"🐦‍🔥 FÊNIX LIVE AI");}
    private void refreshCoach(){int m=minutes(),sc=CoachEngine.score(m,viewers,beans,comments,followers,gifts);String goal=featureGoals&&goalBeans>0?" • "+beans+"/"+goalBeans+" Beans":" • "+beans+" Beans";metrics.setText("⏱ "+m+"m • 👥 "+viewers+" • 💬 "+comments+" • +"+followers+" seg."+goal+(featureStars?" • ⭐"+stars:"")+(featurePk?" • ⚔️"+pk:""));advice.setText("FÊNIX SCORE "+sc+"/100 • "+CoachEngine.scoreLabel(sc)+"\n"+CoachEngine.advise(m,viewers,beans,comments,followers,gifts,featureStars?stars:0,featurePk?pk:0,featureGoals?goalBeans:0));}

    private void showGiftMenu(){ LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL); Button add=b("Registrar presente recebido"),strategy=b("Ver estratégia da meta");l.addView(add);l.addView(strategy); AlertDialog d=new AlertDialog.Builder(this).setTitle("Presentes e meta").setView(l).setNegativeButton("Fechar",null).create(); if(d.getWindow()!=null)d.getWindow().setType(overlayType()); add.setOnClickListener(v->{d.dismiss();gifts++;showNumberDialog("Beans deste presente",value->{beans+=value;refreshCoach();saveSnapshot();});}); strategy.setOnClickListener(v->{advice.setText(CoachEngine.giftStrategy(beans,goalBeans));d.dismiss();}); d.show(); }
    private void showDataDialog(){final EditText v=new EditText(this),c=new EditText(this),f=new EditText(this),be=new EditText(this);v.setHint("Pessoas na sala");c.setHint("Comentários acumulados");f.setHint("Seguidores ganhos");be.setHint("Beans acumulados");v.setInputType(2);c.setInputType(2);f.setInputType(2);be.setInputType(2);v.setText(String.valueOf(viewers));c.setText(String.valueOf(comments));f.setText(String.valueOf(followers));be.setText(String.valueOf(beans));LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(30,10,30,0);l.addView(v);l.addView(c);l.addView(f);l.addView(be);AlertDialog d=new AlertDialog.Builder(this).setTitle("Atualizar desempenho").setView(l).setPositiveButton("Salvar",(x,w)->{viewers=parseInt(v.getText().toString());comments=parseInt(c.getText().toString());followers=parseInt(f.getText().toString());beans=parseLong(be.getText().toString());refreshCoach();saveSnapshot();}).setNegativeButton("Cancelar",null).create();if(d.getWindow()!=null)d.getWindow().setType(overlayType());d.show();}
    private interface LongCallback{void run(long value);} private void showNumberDialog(String title,LongCallback cb){EditText e=new EditText(this);e.setInputType(2);e.setHint("0");AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Adicionar",(x,w)->cb.run(parseLong(e.getText().toString()))).setNegativeButton("Cancelar",null).create();if(d.getWindow()!=null)d.getWindow().setType(overlayType());d.show();}
    private int parseInt(String s){try{return Integer.parseInt(s.trim());}catch(Exception e){return 0;}} private long parseLong(String s){try{return Long.parseLong(s.trim());}catch(Exception e){return 0;}}

    private void toggleTeleprompter(){ if(!featureTeleprompter)return; if(teleprompterView!=null){wm.removeView(teleprompterView);teleprompterView=null;return;} if(script.trim().isEmpty()){Toast.makeText(this,"Defina o roteiro no app antes de iniciar a live.",Toast.LENGTH_LONG).show();return;}
        LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(10,8,10,8);GradientDrawable bg=new GradientDrawable();bg.setColor(0xEE000000);bg.setCornerRadius(24);bg.setStroke(2,0xFFFFB300);box.setBackground(bg);TextView h=t("📝 TELEPROMPTER • arraste para mover",14),body=t(script,20);box.addView(h);ScrollView sv=new ScrollView(this);sv.addView(body);box.addView(sv,new LinearLayout.LayoutParams(-1,340));LinearLayout row=new LinearLayout(this);Button slow=b("Lento"),normal=b("Normal"),fast=b("Rápido"),pause=b("Pausar"),close=b("Fechar");row.addView(slow);row.addView(normal);row.addView(fast);box.addView(row);box.addView(pause);box.addView(close);
        final int[] speed={2};final boolean[] running={true};final Handler auto=new Handler(Looper.getMainLooper());final Runnable scroll=new Runnable(){public void run(){if(teleprompterView==null)return;if(running[0])sv.smoothScrollBy(0,speed[0]);auto.postDelayed(this,50);}};slow.setOnClickListener(v->{speed[0]=1;running[0]=true;});normal.setOnClickListener(v->{speed[0]=2;running[0]=true;});fast.setOnClickListener(v->{speed[0]=4;running[0]=true;});pause.setOnClickListener(v->{running[0]=!running[0];pause.setText(running[0]?"Pausar":"Continuar");});close.setOnClickListener(v->{auto.removeCallbacks(scroll);toggleTeleprompter();});
        WindowManager.LayoutParams lp=new WindowManager.LayoutParams(760,-2,overlayType(),WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,PixelFormat.TRANSLUCENT);lp.gravity=Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL;lp.y=100;h.setOnTouchListener(new View.OnTouchListener(){float x,y;int ox,oy;public boolean onTouch(View v,MotionEvent e){if(e.getAction()==0){x=e.getRawX();y=e.getRawY();ox=lp.x;oy=lp.y;return true;}if(e.getAction()==2){lp.x=ox+(int)(e.getRawX()-x);lp.y=oy-(int)(e.getRawY()-y);wm.updateViewLayout(box,lp);return true;}return false;}});teleprompterView=box;wm.addView(box,lp);auto.postDelayed(scroll,1000);
    }
    private void saveSnapshot(){if(sessionId==null||userId.isEmpty()||token.isEmpty())return;final int m=minutes(),v=viewers,c=comments,f=followers,g=gifts,s=featureStars?stars:0,p=featurePk?pk:0;final long be=beans;final String sid=sessionId;io.execute(()->{try{api.snapshot(sid,userId,m,v,be,c,f,g,s,p);}catch(Exception ignored){}});}
    @Override public void onDestroy(){handler.removeCallbacks(ticker);if(bubble!=null&&wm!=null)try{wm.removeView(bubble);}catch(Exception ignored){}if(teleprompterView!=null&&wm!=null)try{wm.removeView(teleprompterView);}catch(Exception ignored){}if(sessionId!=null&&!token.isEmpty()){final int sc=CoachEngine.score(minutes(),viewers,beans,comments,followers,gifts),finalStars=featureStars?stars:0,finalPk=featurePk?pk:0;final String sid=sessionId;io.execute(()->{try{api.finishSession(sid,beans,viewers,followers,gifts,finalStars,finalPk,sc);}catch(Exception ignored){}});}io.shutdown();super.onDestroy();}
    @Override public android.os.IBinder onBind(Intent i){return null;}
}
